#!/bin/bash

MOUNT=`pwd`
APPNAME=$1
ENVIRONMENT=$2
GITKEEP=$3

if [ "$ENVIRONMENT" = "--gitkeep" ]
then
  GITKEEP="--gitkeep"
  ENVIRONMENT='local'
elif [ -z "$ENVIRONMENT" ]; then
  ENVIRONMENT="local";
fi

mkdir -p $MOUNT/apps/$APPNAME/$ENVIRONMENT   \
         $MOUNT/conf.d/$APPNAME/$ENVIRONMENT \
         $MOUNT/logs/$APPNAME/$ENVIRONMENT   \
         $MOUNT/pids/$APPNAME/$ENVIRONMENT

if [ "$GITKEEP" = "--gitkeep" ]; then
  touch  $MOUNT/apps/$APPNAME/$ENVIRONMENT/.gitkeep   \
         $MOUNT/conf.d/$APPNAME/$ENVIRONMENT/.gitkeep \
         $MOUNT/logs/$APPNAME/$ENVIRONMENT/.gitkeep   \
         $MOUNT/pids/$APPNAME/$ENVIRONMENT/.gitkeep
fi